### ISSUE TITLE
DownAlbum no longer downloads Pinterest boards

### ISSUE THREAD

**Issue by codewizard13** [inDream/DownAlbum#8]
In 2016 I discovered DownAlbum and used it extensively for batch download full, **high-quality Pinterest albums**. I even posted about how great the software was [on Quora](https://www.quora.com/How-can-I-download-all-of-the-full-size-images-from-my-Pinterest-board/answer/Eric-L-Hepperle). 

Unfortunately, it appears that the Chrome extension stopped working very recently. In fact, there are several comments from around a month ago (_January 19, 2019_) stating that **_DownAlbum no longer works_**. I believe the majority of users were using it for Facebook and Instagram, but my main focus is Pinterest.

![DownAlbum extension no longer works comments on Chrome webstore](https://user-images.githubusercontent.com/3443044/52404116-db544880-2a8d-11e9-9282-fa230dc487b3.png)

So, I'm just wondering what changed. Did the extension break because Pinterest changed their site software? If so, why doesn't the Chrome extension work anymore?

This was a valued extension. **_Have you given up on continuing to develop DownAlbum?_**

**Comment by inDream** [comment]
Could you test is it fixed now? Could you provide screenshot  / error message appeared in console?
(Press Win: Ctrl + Shift + J / Mac: Cmd + Opt + J)

**Comment by codewizard13** [comment]
@inDream Yes. I tested it and it is working! Thanks for fixing.

![image](https://user-images.githubusercontent.com/3443044/55906693-79ea4c00-5b9a-11e9-83ca-1f6288b18f07.png)

**Comment by TheGlassEyedVillian** [comment]
The Extension has stopped working Again on Pinterest

**Comment by inDream** [comment]
@TheGlassEyedVillian Could you share the link that not works?

**Comment by tracymc** [comment]
@inDream i'm running into an error on pinterest. This is the link: https://www.pinterest.com/imagekind/art-deco-wall-decor/
I've attached the image
![pinterest error](https://user-images.githubusercontent.com/12902564/70475962-8bb62300-1a8a-11ea-9712-e3752148f8ea.JPG)

**Comment by Redskin77** [comment]
Same problem

**Comment by asdfzxcv5** [comment]
After December 13 update 0.19.12.1
All pinterest can't download
When you run the download
Cannot load initial state
A window called pops up
Extension Program error comes up like this

![DownAlbum error](https://user-images.githubusercontent.com/49179863/70862353-b585b300-1f7e-11ea-807c-707ca3827cbf.jpg)

**Comment by melsilver** [comment]
i have the same issue

**Comment by inDream** [comment]
@tracymc @Redskin77 @asdfzxcv5 @melsilver Pinterest should be fixed now.

**Comment by melsilver** [comment]
cheers for the tag - i'm getting same message , i'll shut the browser and try again

**Comment by melsilver** [comment]
> @tracymc @Redskin77 @asdfzxcv5 @melsilver Pinterest should be fixed now.

i've restarted browser and cleared cache ... still getting same message. Anything else i should try ?. Cheers btw - i love this extension

**Comment by inDream** [comment]
@melsilver just published 0.19.12.3, hope it could solve the issue.

**Comment by melsilver** [comment]
> @melsilver just published 0.19.12.3, hope it could solve the issue.

thank you  :) app store still has 0.19.12.2 ...will it update itself?

**Comment by tracymc** [comment]
@inDream woot! thanks for the fix! love your app

**Comment by melsilver** [comment]
@tracymc  where did you get it please? ta

**Comment by tracymc** [comment]
@melsilver  i didn't reinstall the new version. i just used the one already installed Version
0.19.12.2 and it's working fine for me

**Comment by melsilver** [comment]
ok thanks ...will try again

**Comment by melsilver** [comment]
yay ...it working :) thank you so much @inDream

**Comment by Carolinewk** [comment]
Still not working for me. I put to download and nothing happens. It just appear the window with the countage but it's empty.

**Comment by inDream** [comment]
@Carolinewk Could you send the board link for me to test?

**Comment by Carolinewk** [comment]
Well, it's with all boards I try. I tried to clean the caches and appears
the numbers now (of images being processed) but it's stuck like: 20/2103
(being the last one the number of images in the board). But the first
number is the number of loaded images in MY FEED (the images it's not at
all related with the board im trying to download). It's not the 20 images
processed in the board I'm trying to download.

Em dom, 22 de dez de 2019 04:05, inDream <notifications@github.com>
escreveu:

**Comment by GJS1701** [comment]
I am having exactly the same problem.

![image](https://user-images.githubusercontent.com/59528442/71778479-5d066c00-2fa6-11ea-9937-65f4780933a2.png)

**Comment by inDream** [comment]
@GJS1701 Could you provide screenshot / error message appeared in console?
(Press Win: Ctrl + Shift + J / Mac: Cmd + Opt + J)

**Comment by GJS1701** [comment]
> @GJS1701 Could you provide screenshot / error message appeared in console?
> (Press Win: Ctrl + Shift + J / Mac: Cmd + Opt + J)

There is one in the post above.  There is no error message.  It just stops ate a very low number of pins .

**Comment by melsilver** [comment]
@inDream 
hi - same as above is happening to me today - the output/close box comes up but the download doesnt start  - just says 0/x pins 

any ideas? 
many thanks

**Comment by melsilver** [comment]
deleted and re downloaded and it seems to work again !

**Comment by GJS1701** [comment]
I tried that.  It now says 'status 23/   ' and the after some delay selects 23 random images from my pinterest feed including adverts, and different pinterest albums entirely.

**Comment by SG1Fan1** [comment]
@inDream
hi - same as above is happening to me today - the output/close box comes up but the download doesnt start - just says 0/x pins

Attached Console

![DownAlbum-Console](https://user-images.githubusercontent.com/61110258/74603461-05364700-50b4-11ea-87a3-c706b3647cf7.JPG)

**Comment by GJS1701** [comment]
Now I have the opposite problem.  The number of items just keeps climbing it does not matter how many items on my pinterest board the items keep going.  Example I have 310 pins and I finally stopped Downalbum at 600+.  And it had selected any old rubbish from my Pinterest feed.

**Comment by timbuktu234** [comment]
downalbum not working on Chrome for pinterest?

Press button, select normal, box opens then nothing happens.

It was working perfect until December 10, 2020


![Screen Shot 2020-12-29 at 5 18 35 PM](https://user-images.githubusercontent.com/460897/103320148-34377c00-4a2c-11eb-845f-f5534c10ce3a.jpg)
![Screen Shot 2020-12-29 at 5 17 29 PM](https://user-images.githubusercontent.com/460897/103320151-3699d600-4a2c-11eb-9383-053cc03f4988.jpg)

**Comment by z171181575** [comment]
![微信截图_20210106155503](https://user-images.githubusercontent.com/77045543/103743730-9b11f200-5037-11eb-9771-d57339a54668.png)
![微信截图_20210106155519](https://user-images.githubusercontent.com/77045543/103743744-9e0ce280-5037-11eb-9365-9cdf83afd29e.png)

![微信截图_20210106155503](https://user-images.githubusercontent.com/77045543/103743742-9d744c00-5037-11eb-9896-23a3c51ae6b0.png)
![微信截图_20210106155519](https://user-images.githubusercontent.com/77045543/103743744-9e0ce280-5037-11eb-9365-9cdf83afd29e.png)

**Comment by z171181575** [comment]
not working

**Comment by socrates55** [comment]
Hi, I can't keep using the extension, any solution?
![Sin título](https://user-images.githubusercontent.com/77537068/104813249-ba9edc80-57e6-11eb-9431-e5b82f945362.jpg)

**Comment by LOBEZNO65** [comment]
Goods from Madrid. "Download Album" don´t work for Pinterest.  Have you any solution for? Thanks very much.

**Comment by timbuktu234** [comment]
DownAlbum stopped working on Pinterest around Dec 23, 2020

Developer is from H.K., so maybe the reds got him.
